# SPDX-License-Identifier: GPL-3.0+
# License-Filename: LICENSES/preferred/GPL-3.0

sudo: false
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libpcap-dev
env:
  matrix:
   - EXTRA_CFLAGS=""
   - EXTRA_CFLAGS="-DDEBUG"
   - EXTRA_CFLAGS="-DCLEAR_SCREEN"
   - EXTRA_CFLAGS="-DCLEAR_SCREEN -DDEBUG"
script:
 - make clean V=s && make CC="${CC}" V=s
