# SPDX-License-Identifier: GPL-3.0+
# License-Filename: LICENSES/preferred/GPL-3.0

sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libpcap-dev
env:
  matrix:
   - EXTRA_CFLAGS=""
   - EXTRA_CFLAGS="-DDEBUG"
   - EXTRA_CFLAGS="-DCLEAR_SCREEN"
   - EXTRA_CFLAGS="-DCLEAR_SCREEN -DDEBUG"
script:
 - make clean V=s && make CC="${CC}" V=s

# windows cross-compiler
matrix:
  include:
    - os: linux
      env:
      - MXE_CPU=i686
      - PATH="/usr/lib/mxe/usr/bin/:$PATH"
      - EXTRA_CFLAGS="-DCLEAR_SCREEN"
      addons:
        apt:
          sources:
          - sourceline: 'deb http://pkg.mxe.cc/repos/apt/debian jessie main'
            key_url: 'http://pkg.mxe.cc/repos/apt/conf/mxeapt.gpg'
          packages:
          - curl
          - unzip
          - mxe-i686-w64-mingw32.static-gcc
      before_script:
      - curl https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -o WpdPack_4_1_2.zip
      - unzip WpdPack_4_1_2.zip
      script:
      - make clean V=s && make V=s CROSS="${MXE_CPU}-w64-mingw32.static-" ap51-flash.exe
    - os: osx
      script:
      - make clean V=s && make V=s ap51-flash-osx
